Name = "Proof-of-Personhood Party"
DateTime = "2017-08-08 15:00 UTC"
Location = "Earth, City3"
[[servers]]
  Address = "tcp://192.33.210.8:9204"
  Public = "P1Yom3lJdk85M5hHzHbuICTtA41lJ/ZJD2Qo974KlIM="
  Description = "Conode_3"
[[servers]]
  Address = "tcp://192.33.210.8:9200"
  Public = "jlaPygnTgcFinbxojtFFop1U3DHqfNgWrvftHKf+Ihs="
  Description = "Conode_1"
